#! /bin/bash

# Print CSV file to cli as a Table
function text-column() { sed 's/,,/, ,/g;s/,,/, ,/g' $1 | column -s, -t ;}

# Trim trailing white spaces from each line in input
function wtrim() { sed 's/[ \t]*$//' $1 } 

if [ `uname -o` = "Cygwin" ]; then

    # Perform git push on repository and echo to log file
    function note_push() {
        pushd ${1}
        git push origin --all
        echo "Time: $(date) performed git push on ${PWD##*/}" >> $HOME/logs/Debug.log
        popd
    }

    function cyg-update() {
        wget "https://cygwin.com/setup-x86.exe"
        cygstart -- setup-x86.exe -K http://cygwinports.org/ports.gpg
        rm setup-x86.exe
    }

    function explore() {
        /bin/cygstart --explore "${1:-.}"
    }

fi

function split_flac() {
    INPUT="$1"
    cuebreakpoints $INPUT.cue | shnsplit -O never -o flac $INPUT
}

function ghm() {
    ghi --no-pager "$@" -- GiacofeiHome/maintenance
}

function py_env() {
    ENV=$(find . -maxdepth 3 -wholename "./*bin/activate")
    if [[ -f $ENV ]]; then
        source $ENV
    else
        virtualenv -p /usr/bin/python3.5 env
        source env/bin/activate
    fi
}

