# Beets configuration --------------------------------------------------------
library: ~/share/beets_library.db



import:
    move: yes

# Plugins --------------------------------------------------------------------
plugins: [
    chroma,
    duplicates,
    missing,
    lyrics,
    lastgenre
]

# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]
