# This task queues all of the movies in my IMDB watchlist
IMDB_Movie_Queue:
  priority: 100 # Always run before My_Movies task
  preset: no_global
  interval: 2 hours
  imdb_list:
    username: c.giacofei@gmail.com
    password: cgiacofei
    list: watchlist
    # auto_remove: [ accepted, rejected ] # keep my watchlist clean
  accept_all: yes
  queue_movies: { force: no } # Output entries to movie queue (with any quality)

# The next two tasks download the queue from the previous task effectively implementing
# a 2 day timeframe for 1080p movies, then falls back to 720p
My_Movies-1080p:
  priority: 110
  preset:
    - movies-global
    - movies-queued
  quality: 1080p+ bluray+ h264+ dtshd+

My_Movies-720p:
  priority: 120
  preset:
    - movies-global
    - movies-queued
  quality: 720p+ webdl+ xvid+ !mp3
  torrent_alive:
    min_seeds: 5
  delay: 7 days # Wait 7 days for a 1080p movie before trying downloading 720p


# These task implement the movies-auto preset
Auto_Movies-1080p:
  priority: 130
  quality: 1080p+ bluray+ h264+ dtshd+
  preset:
    - movies-global
    - movies-auto

Auto_Movies-720p:
  priority: 140
  quality: 720p+ dvdrip+ xvid+ !mp3
  preset:
    - movies-global
    - movies-auto
  delay: 7 days # Wait 7 days for a 1080p movie before trying downloading 720p
