# Use a local folder (synced with Dropbox) as a source
# I can drop torrents in this folder and they are synced with Dropbox, always
# accepted, then the original file is deleted
Local_Torrents-TV:
priority: 1
preset:
  - tv-global
  - tv-my_shows
disable_builtins: [seen, seen_info_hash]
disable_plugin:
  - inputs
  - exists_series
  - regexp
  - content_size
  - torrent_alive
all_series:
  parse_only: yes
plugin_priority:
  exec: 0
listdir: /home/chris/Dropbox/torrents/TV
exec:
  on_output:
    for_accepted: rm '/home/chris/Dropbox/torrents/TV/{{title}}.torrent'
accept_all: yes

# Same as above but for movies
Local_Torrents-Movies:
  priority: 2
  preset:
    - movies-global
  disable_builtins: [seen, seen_info_hash]
  disable_plugin:
    - inputs
    - exists_movie
    - seen_movies
    - regexp
    - content_size
    - torrent_alive
    - interval
  # Mark movies as seen
  movie_queue: yes
  plugin_priority:
    exec: 0
  listdir: /home/chris/Dropbox/torrents/Movies
  exec:
    on_output:
      for_accepted: rm '/home/chris/Dropbox/torrents/Movies/{{title}}'
  accept_all: yes
