#!/bin/bash

echo '*********************************'
echo '***** Adding Sources to Apt *****'
echo '*********************************'
echo ''

sources[0]='deb http://linux.dropbox.com/debian wheezy main'
sources[1]='deb ftp://ftp.debian.org/debian stable main contrib non-free'

keys[0]='pgp.mit.edu --recv-keys 5044912E'
ADD=0

for source in "${sources[@]}"; do
	if grep -Fxq "$source" /etc/apt/sources.list; then
		echo '--' $source': Source already present'
	else
		echo '--' $source': Adding source to /etc/apt/sources.list'
		echo "$source" >> /etc/apt/sources.list
		ADD=1
	fi
done

echo ''
echo '***** Adding GPG Keys to Apt ****'
echo ''

for key in "${keys[@]}"; do
	echo -- 'Adding GPG key' $key
	apt-key adv --keyserver "$key"
	echo ''
done

etckeeper commit 'Added sources to sources.list'
